In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
a = np.random.randn(10)
a

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [4]:
b = np.random.randn(10)
b

array([-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ])

In [5]:
a * b

array([-0.23018613,  0.0643938 ,  0.15671619, -2.91398294,  0.40389533,
        0.13165229, -1.59947589,  0.24116432,  0.42629405, -0.76625956])